### ISSUE TITLE
Issues with daphnia output?

### ISSUE THREAD

**Issue by rjp5nc** [awedwards/daphnia#18]
Before going through the ~7300 pictures, we took a minute to stop and compare the before and after files. Some of the columns do not appear to be getting recalculated after changing and saving the image in the gui (i.e., animal length, etc.). We weren't sure if these should've been changed, as in some of them the fit was pretty badly miscalculated. At least one set of columns (AR and AS when it is changed into an excel sheet) are switched with each other. The tail dorsal coordinates has also gone from a set of coordinates, into a single number. Attached is a single example from one of the images that we had worked on. It had been flipped, and corrected. Could you double check some images to make sure that it is actually recalculating the values that need to be recalculated? The files are daphnia_output_20180926 as the original, and daphnia_output_xaa_20181010 as the output. We have gone all the way to xaf, (xaa, xab...xaf), with 50 images per file. We used the terminal's diff to get several comparisons. 

[example_pheno-output.txt](https://github.com/awedwards/daphnia/files/2502496/example_pheno-output.txt)

**Comment by awedwards** [comment]
Yes, i'll take a look. Thanks for the details. Sorry it's not right -- I think I will have time to fix it in the next day or two.

**Comment by awedwards** [comment]
Is the example you attached one where the ventral-dorsal axis was flipped?

**Comment by rjp5nc** [comment]
Yes, the example one was flipped, which probably explains why some of the measurements turned from negative to positive, or vice versa. It was one of the "worst" ones that we could find, that had something wrong with it. ie, it was flipped, the masking was pretty wrong, etc.

**Comment by awedwards** [comment]
Cool. If it was flipped, then that definitely explains the columns switching values (specifically dorsal/ventral points/vectors). I'll double check the other values though, since we shouldn't be having points change to single values.

**Comment by beckerdoerthe** [comment]
Thanks Austin. Yep, if the script could just update all the traits/parameters we are aiming to measure (i.e., daphnia_output.txt file) that'd be great! I assume the shape.txt file is updating the fit info based on the new (= modified) fits? (I did not check on this at all).

**Comment by awedwards** [comment]
Yeah, I thought I was updating animal_length before, but I missed it. I'll check the shape data when I get back from lunch.

Also, I found another bug that will break things, so I'll fix that after lunch too. 🗡

**Comment by awedwards** [comment]
OK, i think all of the output/shape issues are fixed. If you or Robert could double check if your shape data is being saved, that would be great. The easiest way to do that would be to set 'skip_accepted' to 0 and show something you've already saved. If it looks like it's fixed then we are in business.

THANKS! 😄

**Comment by beckerdoerthe** [comment]
Awesome! Will check it out tomorrow. Thx.

**Comment by rjp5nc** [comment]
It appears to be getting saved, but there still appears to be an issue. When bringing it up again, it creates another checkpoint off of the dorsal line. This happens in a good number of the pictures I just tested. Also, all of the images that we did before this no longer have the correct dorsal line. 

Adding section:
![screen shot 2018-10-26 at 8 34 03 am](https://user-images.githubusercontent.com/43250118/47566978-47ee7180-d8fb-11e8-97f0-c631989ed60f.png)
![screen shot 2018-10-26 at 8 33 07 am](https://user-images.githubusercontent.com/43250118/47566982-4cb32580-d8fb-11e8-963d-f403e28bc3f0.png)

Old Image:
![screen shot 2018-10-26 at 8 45 49 am](https://user-images.githubusercontent.com/43250118/47567088-9b60bf80-d8fb-11e8-8a1a-211e400b1c73.png)

**Comment by beckerdoerthe** [comment]
I can only try this next week, but @rjp5nc you might have a moment tomorrow to try (maybe)?

**Comment by rjp5nc** [comment]
Sure, I can test it out tomorrow morning.

**Comment by awedwards** [comment]
Oh shoot. So you will want to re-copy the shape_output.txt file from /mnt/spicy_4/daphnia/analysis/analysis_results/ (I think that's the right path). I had to make some changes to the structure of that file, so your local copy needs to be updated. Sorry about that.

**Comment by rjp5nc** [comment]
When saving, it now appears to give this error. It still does save the information in the truncated version, though.

![screen shot 2018-11-06 at 8 19 13 am](https://user-images.githubusercontent.com/43250118/48070230-5f541700-e1a5-11e8-809b-1fbfc0e75d73.png)

**Comment by rjp5nc** [comment]
Not sure if this is also a part of that,  but when moving on to another picture after saving, even if that error isn't given, it seems the gui crashes.

**Comment by rjp5nc** [comment]
Were you ever able to get all of the other output features to update? Such as dorsal area etc? The tail base appears to be nan in the current output. Is that supposed to be like that for some of these pictures? Also, when you modified the structure of the shape output, it didn't update any of the previous ones that we had already done (All of the other outputs without "test").

**Comment by awedwards** [comment]
Ok, I believe I fixed the saving/next image bug. Let me know if there are more issues with that.

Regarding the output features, they should all be updating in real time as you move points around. I can do a thorough triple-check just to make sure (I'll let you know when I've done that), but as always, let me know if something looks off. I fixed the tail_base thing. We aren't really using it for anything as far as I know (it's basically the midpoint between tail and tail_dorsal) but I guess we can add it back in just in case.

I don't know what to do about the shape output not updating. I suspect it didn't get saved properly, and I fear those might have to be re-done... sorry about that. I think it would be a good idea to set skip_accepted to 0, especially when you're setting things up on a new computer, just to make sure that things are being saved properly before you fix 100s of images.
